name: Build

on:
  push:
    branches: [release-build]
  pull_request:
    branches: [release-build]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true

  audit:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo ${{env.tag}}

  deploy:
    runs-on: ubuntu-latest
    needs: audit
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . -f ./build/Dockerfile --tag beancodede/authi:latest --tag beancodede/authi:${{ env.tag }}
      
      - name: Push the Docker image
        run: docker push beancodede/authi:latest