name: journeytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3

      - name: Start environment
        run: docker compose --env-file ./deployments/main.env --file ./deployments/docker-compose.yml up --build --force-recreate -d

      - name: Journeytests
        run: go test ./test -v
      
      - name: Shutdown environment
        run: docker compose --env-file ./deployments/main.env --file ./deployments/docker-compose.yml down