name: Main Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v3

      - name: Unit test
        run: go test ./internal/... -v
  journey_test:
    needs: [unit_test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v3

      - name: Start environment
        run: docker compose --env-file ./deployments/main.env --file ./deployments/docker-compose.yml up --build --quiet-pull --force-recreate -d

      - name: Journeytests
        run: go test ./test -v
      
      - name: Shutdown environment
        run: docker compose --env-file ./deployments/main.env --file ./deployments/docker-compose.yml down
