name: Main Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3

      - name: Unit test
        run: go test ./internal/... -v

  journey_test:
    needs: [unit_test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3

      - name: Start environment
        run: docker compose --env-file ./deployments/main.env --file ./deployments/docker-compose.yml up --build --quiet-pull --force-recreate -d

      - name: Journeytests
        run: go test ./test -v
      
      - name: Shutdown environment
        run: docker compose --env-file ./deployments/main.env --file ./deployments/docker-compose.yml down
  
  build:
    needs: [journey_test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build docker build . -f ./build/Dockerfile --tag beancodede/authi:$(date +%s)
      
      - name: Push the Docker image
        run: docker push beancodede/authi:$(date +%s)